[tool.poetry]
package-mode = false

[tool.poetry.dependencies]
python = "^3.12"
internetarchive = "^3.6.0"
gitpython = "^3.1.43"
markdown2 = "^2.4.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
